### ISSUE TITLE
Fix shellcheck warnings after PR 14 / Issue 12

### ISSUE THREAD

**Issue by thomasmerz** [ct-Open-Source/ctraspion#15]
There are some errors and warnings in your scripts that really should be fixed. See detailled report in my [GH Action](https://github.com/thomasmerz/ctraspion/actions/runs/3765393809/jobs/6400824550).

I will fix them and make a PR in the holidays.

**Comment by psct** [comment]
Done in 83799ae

**Comment by thomasmerz** [comment]
Uh, did I "forgot" to make a PR? 😜 Thanks, great checking! 👍🏼
