### ISSUE TITLE
v111: Installation leider fehlgeschlagen in Zeile 159.

### ISSUE THREAD

**Issue by halbtagsprogrammierer** [ct-Open-Source/ctraspion#16]
Bei mir bricht das Installationsskript mit folgender Meldung ab:
**Installation leider fehlgeschlagen in Zeile 159.**

Ich habe das "Pi OS Legacy (Debian Buster)" Image von der Projektseite runtergeladen und installiert. Weil sich dann der Download der raspion.zip weigerte, habe ich erstmal das OS mittels "sudo apt update/upgrade" aktualisiert und rebootet.

Danach habe ich die Installation wie im Artikel beschrieben installiert:
```
wget ct.de/s/x5Pm -O raspion.zip
unzip raspion.zip
cd raspion
./install.sh
```   

Dann erschien folgende Meldung:

```
pi@raspion:~/raspion $ ./install.sh
==> Einrichtung des c't-Raspion (v111)
* Wifi einschalten
* Hilfspakete hinzufügen, Paketlisten aktualisieren
* Firewallregeln vorbereiten, Module laden
* Pakete vorkonfigurieren ...
* Firewall-Regeln speichern ...
* Pi OS aktualisieren ...
* Pi OS Sprachanpassungen ...
* Pakete installieren ...
* Softwaregrundkonfiguration ...
* systemd-Units vorbereiten ...
* Weboberfläche hinzufügen ...
* Pi-hole installieren ...
Installation leider fehlgeschlagen in Zeile 159.
```   

In Zeile 159 steht das hier:

```
sudo chattr -f -i /etc/init.d/pihole-FTL >> $LOG 2>&1
```

Ein 2. Versuch, das Installationsscript auszuführen brachte den identischen Abbruch, wieder Zeile 159.

Einmal manuell "sudo chattr -f -i /etc/init.d/pihole-FTL" auszuführen brachte keine Besserung.

**Comment by halbtagsprogrammierer** [comment]
Das Log habe ich hier angehängt.

[raspion.log](https://github.com/ct-Open-Source/ctraspion/files/10731176/raspion.log)

**Comment by psct** [comment]
Danke, fix ist in v112

**Comment by halbtagsprogrammierer** [comment]
Danke enbenfalls für den schnellen fix!
Neuinstallation hat mit v112 einwandfrei geklappt.
